### ISSUE TITLE
About image data in MDR dataset

### ISSUE THREAD

**Issue by yuchen-hong** [boomluo02/ADMFlow#1]
Hello, thank you for your excellent work!
I wonder if you could release frames that corresponds to the event data?
Thank you for your attention and I'm looking forward to your reply.

**Comment by boomluo02** [comment]
I apologize for the late reply as I have been busy attending conferences lately. Thank you very much for your valuable suggestions, I will organize and release the images of the two frames before and after the event stream recently. Best wishes!

**Comment by yuchen-hong** [comment]
Very grateful for your reply. 
Bset regards! ^v^

**Comment by xiaoyaolovlife** [comment]
Hello, thank you for your work. I really need all the high-frame-rate images corresponding to the event. I wonder if I can obtain them from you. Thank you!
