### ISSUE TITLE
About event data in MDR dataset

### ISSUE THREAD

**Issue by ZPJ-LEFT** [boomluo02/ADMFlow#3]
Hello! 
Your work is very meaningful. 
Now I would like to use event data of MDR dataset, but I find that only the voxel data are published. Do you have any plans to publish the original event data?

**Comment by boomboomluo** [comment]
Hi, I'm sorry for the confusion. What we are releasing is the raw event data, we use Pandas.Dataframe data format to store it, the dictionary keywords are the four elements of the event "x", "y", "t", "p" . We use loader
get_compressed_event() function in the loader/loader_utils.py file to load the event data. You can follow a similar approach to transform the data into the form you want.
I hope this could help you, sincerely.

**Comment by ZPJ-LEFT** [comment]
Thanks! 
And I have another question about the event data.

According to the description in the paper, we can get E(tk-1, tk) and E(tk, tk+1) for predicting F(tk-1, tk). Is it possible to get E(tk-2, tk-1) from the currently released data? 

These data is necessary for some previous event optical flow methods, such as ERAFT.

![图片1](https://github.com/boomluo02/ADMFlow/assets/139030020/ce874693-c4a0-4944-a70a-a17cc381daf7)

**Comment by boomluo02** [comment]
Sorry, our dataset cannot provide more than two consecutive event sequences. This is because we are rendering the data with randomized camera start and end positions, which increases the diversity of viewpoints.
